#!/usr/bin/env python
import os
import sys
import gzip
import re
import random

################################################################################
## Make representative sequence database file.
################################################################################

## A file generated by running make-eggnogv4-seq_list.py.
filename_seq_list = 'eggnogv4.seq_list'

## A file generated by running make-eggnogv4-core_fa.py.
filename_core_fa = 'eggnogv4.proteins.core.fa.gz'

if( not os.access(filename_seq_list,os.R_OK) ):
    sys.stderr.write('%s is not available. Exit.\n'%filename_seq_list)
    sys.exit(1)

if( not os.access(filename_core_fa,os.R_OK) ):
    sys.stderr.write('%s is not available. Exit.\n'%filename_core_fa)
    sys.exit(1)

seq_h = ''
seq_list = dict()
f_fa = gzip.open(filename_core_fa,'rb')
for line in f_fa:
    if( line.startswith('>') ):
        seq_h = line.strip().lstrip('>')
        seq_list[seq_h] = []
    else:
        seq_list[seq_h].append(line.strip())
f_fa.close()

f_og = dict()
f_seq_list = open(filename_seq_list,'r')
for line in f_seq_list:
    if( line.startswith('#') ):
        continue
    tokens = line.strip().split("\t")
    og_id = tokens[0]
    og_name = re.sub(r'[0-9]+','',og_id)
    if( not f_og.has_key(og_name) ):
        filename_rep_pep = 'eggnogv4_%s_rep.fa'%og_name
        sys.stderr.write('Write %s\n'%filename_rep_pep)
        f_og[og_name] = open(filename_rep_pep,'w')
    median_id_list = tokens[3].split(';')
    random.shuffle(median_id_list)
    rep_id = median_id_list[0]
    f_og[og_name].write('>%s|%s\n%s\n'%(og_id,rep_id,''.join(seq_list[rep_id])))
f_seq_list.close()

for og_name in f_og.keys():
    f_og[og_name].close()
